/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import models.User;

/**
 *
 * @author Administrator
 */
public class frmWelcome extends javax.swing.JFrame {

    private User user;

    /**
     * Creates new form Welcome
     */
    public frmWelcome() {
        initComponents();
    }

    public frmWelcome(User user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.user = user;
        showControl();
    }

    private void showControl(){
        lblUsername.setText(user.getUsername());
        
        int per = user.getPer();
        
        System.out.println(user.getPer());
        switch (per) {
            case 0:{
                lblControl.setText("Read");
                break;
            }
                
            case 1:{
                lblControl.setText("Write");
                break;
            }
                
            case 2:
            {
                lblControl.setText("Full control");
                break;
            }
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblControl = new javax.swing.JLabel();
        btnOpenLab202 = new javax.swing.JButton();
        btnOpenLab201 = new javax.swing.JButton();
        btnOpenLab304 = new javax.swing.JButton();
        btnOpenLab04_1 = new javax.swing.JButton();
        btnOpenLab04_2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("Welcome:");

        lblUsername.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 0, 0));
        lblUsername.setText("username");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("Control: ");

        lblControl.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblControl.setText("control");

        btnOpenLab202.setText("Open Form Lab2_2");
        btnOpenLab202.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenLab202ActionPerformed(evt);
            }
        });

        btnOpenLab201.setText("Open Form Lab2_1");
        btnOpenLab201.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenLab201ActionPerformed(evt);
            }
        });

        btnOpenLab304.setText("Open Form Lab3_4");
        btnOpenLab304.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenLab304ActionPerformed(evt);
            }
        });

        btnOpenLab04_1.setText("Open Form Lab4_1");
        btnOpenLab04_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenLab04_1ActionPerformed(evt);
            }
        });

        btnOpenLab04_2.setText("Open Form Lab4_2");
        btnOpenLab04_2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                btnOpenLab04_2AncestorRemoved(evt);
            }
        });
        btnOpenLab04_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenLab04_2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsername)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblControl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOpenLab201, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnOpenLab304)
                            .addComponent(btnOpenLab04_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnOpenLab04_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenLab202, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblControl))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpenLab201)
                    .addComponent(btnOpenLab202))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpenLab304)
                    .addComponent(btnOpenLab04_1))
                .addGap(18, 18, 18)
                .addComponent(btnOpenLab04_2)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenLab202ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenLab202ActionPerformed
        // TODO add your handling code here:
        System.out.println(user.getPer());
        frmLab02_2 frm = new frmLab02_2(user.getPer());
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnOpenLab202ActionPerformed

    private void btnOpenLab201ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenLab201ActionPerformed
        // TODO add your handling code here:
        frmLab02 frm = new frmLab02();
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnOpenLab201ActionPerformed

    private void btnOpenLab304ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenLab304ActionPerformed
        // TODO add your handling code here:
        frmLab03_4 frm = new frmLab03_4();
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnOpenLab304ActionPerformed

    private void btnOpenLab04_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenLab04_1ActionPerformed
        // TODO add your handling code here:
        frmLab04_01 frm = new frmLab04_01();
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnOpenLab04_1ActionPerformed

    private void btnOpenLab04_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenLab04_2ActionPerformed
        // TODO add your handling code here:
        frmLab04_02 frm = new frmLab04_02();
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnOpenLab04_2ActionPerformed

    private void btnOpenLab04_2AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnOpenLab04_2AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenLab04_2AncestorRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmWelcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenLab04_1;
    private javax.swing.JButton btnOpenLab04_2;
    private javax.swing.JButton btnOpenLab201;
    private javax.swing.JButton btnOpenLab202;
    private javax.swing.JButton btnOpenLab304;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblControl;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
