/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui_lab5;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import models.User;

/**
 *
 * @author huynh
 */
public class frmFTPClient extends javax.swing.JFrame {

    private static final int PORT = 10000;
    private User user;
    private String path;
    private Socket socket = null;

    /**
     * Creates new form frmFTPClient
     */
    public frmFTPClient() {
        initComponents();
    }

    public frmFTPClient(DefaultListModel md, User user) {
        initComponents();
        this.user = user;
        lstPath.setModel(md);
        setDefautlControl(false);
        JOptionPane.showMessageDialog(null, "Please connect to the server first to continue!");
    }

    public void setDefautlControl(boolean isOn) {
        btnBrowse.setEnabled(isOn);
        btnDownload.setEnabled(isOn);
        btnUpload.setEnabled(isOn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fchPath = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        txtDomain = new javax.swing.JTextField();
        btnUpload = new javax.swing.JButton();
        btnDownload = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstClientPath = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPath = new javax.swing.JList<>();
        btnBrowse = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnConnect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Domain");

        btnUpload.setText("upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        btnDownload.setText("download");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstClientPath);

        jScrollPane2.setViewportView(lstPath);

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Client's Folder");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Server Folder");

        btnConnect.setText("Connect Server");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 396,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(135, 135, 135)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(63, 63, 63))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnBrowse)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnConnect))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(txtDomain,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 235,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnUpload)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnDownload)))))
                                .addGap(39, 39, 39)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(txtDomain, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnUpload)
                                        .addComponent(btnDownload))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnConnect))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263,
                                                Short.MAX_VALUE))
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        fchPath.setVisible(true);
        fchPath.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        if (fchPath.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                path = fchPath.getSelectedFile().getCanonicalPath();
                File dir = new File(path);
                File[] files = dir.listFiles();
                if (files == null) {
                    JOptionPane.showMessageDialog(null, "Path wrong!");
                } else {
                    try {
                        DefaultListModel dm = new DefaultListModel();
                        for (File file : files) {
                            dm.addElement(file.getName());
                        }
                        lstClientPath.setModel(dm);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e.toString());
                    }
                }
            } catch (Exception e) {
            }
        }
    }// GEN-LAST:event_btnBrowseActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        try {
            InetAddress ia = InetAddress.getByName(txtDomain.getText());
            try {
                socket = new Socket(ia, PORT);
                String file_name = (String) lstClientPath.getSelectedValue();
                String cpath = path + "\\" + file_name;
                System.out.println(user.getPath());
                System.out.println(cpath);
                System.out.println("path user: " + user.getPath());
                PrintWriter pw = new PrintWriter(socket.getOutputStream());
                pw.println("UPLOAD");
                pw.flush();
                pw.println(user.getPath());
                pw.flush();
                System.out.println("upload command send to the server");
                pw.println(file_name);
                pw.flush();

                System.out.println("file name send to the server");

                BufferedOutputStream bos = new BufferedOutputStream(socket.getOutputStream());
                DataOutputStream dos = new DataOutputStream(bos);

                BufferedInputStream bis = new BufferedInputStream(new FileInputStream(cpath));
                byte[] buf = new byte[bis.available()];
                bos.write(bis.read(buf));
                System.out.println("Data of file send to the server");
                System.out.println("data is: " + buf);
                bos.flush();
                Scanner sc = new Scanner(socket.getInputStream());
                String cmd = sc.nextLine();
                System.out.println("Received respone from the server");
                if (cmd.equals("RECEIVED")) {
                    JOptionPane.showMessageDialog(null, "File send successful");
                } else {
                    JOptionPane.showMessageDialog(null, "File send failed");
                }

                updateFolderServer();
                bos.close();
            } catch (Exception e) {
                System.out.println("err: " + e);
            }
        } catch (UnknownHostException e) {
        }
    }// GEN-LAST:event_btnUploadActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDownloadActionPerformed
        // TODO add your handling code here:
        String file_name = (String) this.lstPath.getSelectedValue();
        System.out.println("file name: " + file_name);
        try {
            PrintWriter pw = new PrintWriter(socket.getOutputStream());
            pw.println("DOWNLOAD");
            pw.flush();
            System.out.println("download command send to the server");
            pw.println(user.getPath());
            pw.flush();
            pw.println(file_name);
            pw.flush();

            System.out.println("Waiting for the server to send the file");
            String cpath = path + "\\" + file_name;
            FileOutputStream fos = new FileOutputStream(new File(cpath));
            BufferedOutputStream bos = new BufferedOutputStream(fos);
            BufferedInputStream bis = new BufferedInputStream(socket.getInputStream());
            byte[] buf = new byte[bis.available()];
            bos.write(bis.read(buf));
            bos.flush();
            bos.close();
            pw = new PrintWriter(socket.getOutputStream());
            pw.println("RECIVED");
            pw.flush();
            updateFolderClient(cpath);
        } catch (Exception e) {
        }

    }// GEN-LAST:event_btnDownloadActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConnectActionPerformed
        // TODO add your handling code here:
        try {
            InetAddress ia = InetAddress.getByName(txtDomain.getText());
            try {

                if (socket != null) {
                    socket.close();
                    JOptionPane.showMessageDialog(null, "Disconnected!");
                    setDefautlControl(false);
                    btnConnect.setText("Connect");
                    txtDomain.setText("");
                } else {
                    socket = new Socket(ia, PORT);
                    JOptionPane.showMessageDialog(null, "Connected!");
                    setDefautlControl(true);
                    btnConnect.setText("Disconnect");
                }
            } catch (Exception e) {
            }
        } catch (UnknownHostException e) {
        }
    }// GEN-LAST:event_btnConnectActionPerformed

    public void updateFolderClient(String cpath) {
        System.out.println("updateFolderClient cpath: " + cpath);
        File dir = new File(cpath);
        File[] files = dir.listFiles();
        if (files == null) {
            // JOptionPane.showMessageDialog(null, "Path is wrong");
        } else {
            try {
                DefaultListModel dm = new DefaultListModel();
                for (File file : files) {
                    dm.addElement(file.getName());
                }

                lstClientPath.setModel(dm);
                this.validate();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public void updateFolderServer() {
        try {
            BufferedInputStream bi = new BufferedInputStream(socket.getInputStream());
            Scanner sc = new Scanner(bi);
            DefaultListModel dm = new DefaultListModel();

            int len = sc.nextInt();
            System.out.println("Received length of files from server");
            for (int i = 0; i < len; i++) {
                dm.addElement(sc.next());
            }

            System.out.println("File list displayed successfully");

            lstPath.setModel(dm);
            this.validate();
            bi.close();
        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFTPClient.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFTPClient.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFTPClient.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFTPClient.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFTPClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnUpload;
    private javax.swing.JFileChooser fchPath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstClientPath;
    private javax.swing.JList<String> lstPath;
    private javax.swing.JTextField txtDomain;
    // End of variables declaration//GEN-END:variables
}
